### ISSUE TITLE
Readme clarify 

### ISSUE THREAD

**Issue by zlatko-minev** [qiskit-community/quantum-prototype-template#38]
### What is the expected enhancement?

On the front page readme: 
"This template repository makes creating new quantum prototype projects much easier for our team."

Optional suggestion: Maybe clarify a bit, might help people browsing get a quicker orientation if relevant to them and which team and types of projects this refers to 

Great work!

**Comment by calebj15** [comment]
Thanks for the feedback! Opening paragraph of README has been written more clearly.

**Comment by calebj15** [comment]
Re-opening to continue discussion of README improvement
