### ISSUE TITLE
Improve Issue Templates

### ISSUE THREAD

**Issue by caleb-johnson** [qiskit-community/quantum-prototype-template#44]
### What is the expected enhancement?

Let's decide on what fields we will require for each type of issue template, and let's decide on the minimum acceptable content for each field.

### Justification
As the number of prototypes grows, we need to become more stringent on which issues we assign and resolve, and which issues we kick back. Currently, our issue templates do not have questions which are direct enough. For example, we should ask specific questions about the operating system and Python version on any bug report.

**Comment by garrison** [comment]
See also https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/ for another approach.

**Comment by pedrorrivero** [comment]
Some more info on how to use YAML syntax for issue forms: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
