### ISSUE TITLE
Add the integration to Qiskit Ecosystem

### ISSUE THREAD

**Issue by mickahell** [qiskit-community/quantum-prototype-template#62]
### What is the expected behavior?
It could be usefull to already have the config file ready in order to add the project to the Qiskit Ecosystem from the beginning.
--> [docs](https://github.com/qiskit-community/ecosystem/blob/main/docs/project_overview.md#ecosystem-test-configuration)

#### Detailes
- Add `ecosystem.json` config file (⚠️ python version as 3.9 or 3.10 ?)
- Add json lint in tox (and Actions + Travis)
- Update [glossary](https://github.com/qiskit-community/quantum-prototype-template/blob/main/docs/file-map-and-description.md)

**Comment by mickahell** [comment]
@garrison @caleb-johnson if it's ok for you I can do it :)

**Comment by caleb-johnson** [comment]
> @garrison @caleb-johnson if it's ok for you I can do it :)

Sure, feel free to submit a PR :)
